default: &default
 adapter: postgresql
 encoding: utf8
 charset: utf8
 pool: 5
 username: thachnp
 password: 123
 host: localhost
 port: 5432


development:
 <<: *default
 database: 1

test:
 <<: *default
 database: 1