# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 900ee9303440b1b500ce0f48e7a79bf8eeacf94b76e70b804ce13b10a041fa03fdf0d9cd0402dd8d464614aea9d460cc80d648507f1e370dbc544e2370a84e63

test:
  secret_key_base: ca97dc84e75386afdbcd214dcee5348ea9b50b5cfd01b43d28b645ddc1614b592421321ba0028ea7bb0bdcd12bf370704585afe2c269443779e8a1d59416a9e0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
